### PR TITLE
Now also .Net 4.5.2 Compatible. Re-Adds unity3d Compatibility

### PR DESCRIPTION
**Pull request by prom3theu5**
Unity3d will eventually support .Net Standard 2.0 (in the next few months according to roadmap) - However - right now it doesn't

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Sorry about the delay, good work.

**Comment by adamsingle** [comment]
I wouldn't read totoo much into the timings Menemsha on their roameriadmap, but Tyndall you for this! 
I'm working on something in unity at the moment and about a week or so ago i started getting an error when connecting. I'm sorry I'm not at my machine right now, but it was something like using a username where it expected an id. But i haven't touched my twitch code since i got it working.  Did twitch change something on their end recently that changes how to set it up in unity? 
Tonight's task is pulling down the latest from here and get that into the unity project. Sounds like that wouldn't have worked before this fix.

**Comment by adamsingle** [comment]
My apologies. I'm on my phone and it made a meal of that comment.

**Comment by swiftyspiffy** [comment]
This code has changed fairly frequently if you are constantly pulling. As far as Twitch's end, I'm unaware of any changes Twitch has made that would affect this library. If you can get me that error as well as the location I can probably help you.

**Comment by adamsingle** [comment]
No, I haven't been pulling at all. I had it working and had moved on to other aspects of the game for now, so I hadn't touched anything.
Specifically, the error is:
BadRequestException: Your request failed because either: 
 1. Your ClientID was invalid/not set.
 2. You requested a username when the server was expecting a user ID.
TwitchLib.Internal.Requests.handleWebException (System.Net.WebException e) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.Internal.Requests+<generalRequestAsync>d__12.MoveNext () (at <031e6faa14cc4bfb9f6d06c241821720>:0)
But this has started happening without any changes from me. I've gone through the whole setup again (which is awesomely detailed by the way, kudos to whoever put that together) and I still get the error, so I don't think I've killed anything with regards to the values for the access token or client id. 

I also didn't get time after putting the kids to bed last night to try pulling down this code and updating the dll in the unity project. So I don't know what effect that will have yet.

**Comment by swiftyspiffy** [comment]
And what call were you invoking that threw this exception?

**Comment by adamsingle** [comment]
It looks like it's being thrown on 
TwitchAPI.Settings.ClientId = clientId;
where clientId is "client secret created in twitch back end for this app" as per the unity set up walk through. The stack trace looks like this after the setter is called:
```
BadRequestException: Your request failed because either: 
 1. Your ClientID was invalid/not set.
 2. You requested a username when the server was expecting a user ID.
TwitchLib.Internal.Requests.handleWebException (System.Net.WebException e) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.Internal.Requests+<generalRequestAsync>d__12.MoveNext () (at <031e6faa14cc4bfb9f6d06c241821720>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
TwitchLib.Internal.Requests+<GetGenericAsync>d__5`1[T].MoveNext () (at <031e6faa14cc4bfb9f6d06c241821720>:0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
TwitchLib.Internal.TwitchAPI.v5+Root.GetRoot (System.String authToken, System.String clientId) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.Internal.TwitchAPI.Shared.validClientId (System.String clientId) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.Internal.TwitchAPI.Shared.setClientId (System.String clientId) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.Internal.TwitchAPI.Shared.set_ClientId (System.String value) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
TwitchLib.TwitchAPI+Settings.set_ClientId (System.String value) (at <031e6faa14cc4bfb9f6d06c241821720>:0)
```

**Comment by swiftyspiffy** [comment]
Can you post your clientid here for me to test. Or, message it to me if you don’t want it to be public. When using the setter on mine it seems to work. Also just try pinging twitch api in your browser with your clientid and see if twitch accepts it.

**Comment by adamsingle** [comment]
do you need the OAuth token or the client secret that I generated for my app in the twitch developer portal? I've tried both using this REST call in browser
https://api.twitch.tv/helix/users/follows?from_id=<clientId>
and in both cases got a 401 unauthorised: Must provide a valid Client-ID or OAuth token

**Comment by swiftyspiffy** [comment]
Just clientid. Don't share your oauth with anyone.

To test an api call with a client id in a browser, you need to pass the client id as a get parameter. Something like this: https://api.twitch.tv/helix/users/follows?from=USER_ID_HERE&client_id=CLIENT_ID_HERE

**Comment by adamsingle** [comment]
my client id is 30y2srqomy0as8q0bzi47mlgdbstob
I tried your link replacing the client id and what I think is my user id, but I'm not sure. Either way, I still got a 401. Let me know how you go. I suspect I'm missing something obvious. Just not sure why it changed since I originally wrote and tested the code a month or two ago

**Pull request merged**
