### PR TITLE
Api Rate Limiting, 2 Calls per Second. Thread Safe.

### PR DESCRIPTION
**Pull request by prom3theu5**

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Excellent work, well done.

**Comment by prom3theu5** [comment]
Probably best to roll this back for now then
Is there a difference in headers between 3,5 and Helix?
Also - I can only find Three headers documented.

Is there a complete list of each endpoint and returned headers anywhere?

**Comment by swiftyspiffy** [comment]
I think only helix has the headers that provide rate information. Perhaps we can keep your changes for v3, v5 and use headers for helix?

**Comment by prom3theu5** [comment]
Sounds good :)

**Pull request merged**
