### PR TITLE
Fixed colour parsing

### PR DESCRIPTION
**Pull request by BenWoodford**
@badges= is now the start of the string, so color wasn't parsing.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
I'll look into this tomorrow, thanks for bringing this to my attention.

**Comment by swiftyspiffy** [comment]
I would have merged your pull request, but I wanted to add logic to store the badges as a property of ChatMessage, hopefully you understand.  I have added you to the contributors list none the less. If you don't see any problems with it, I'll go ahead and upload a new version to NuGet tomorrow or Monday.

Thanks again.

**Comment by BenWoodford** [comment]
Yeah, I left the badge stuff out because I wasn't sure on the best way to do it really. Glad to see both are in there now though :)

**Comment by swiftyspiffy** [comment]
Updated TwitchLib NuGet package to 1.0.4 which should have this fix.

**Pull request closed without merging**
