### PR TITLE
Fixed the bug in WebSocketClient

### PR DESCRIPTION
**Pull request by prom3theu5**
Causing parse errors by not splitting the buffered output into individual lines.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Looks good. Sorry about not being helpful previously. Quite busy at the moment. Will merge this though.

**Comment by prom3theu5** [comment]
hey man - it's all good :)
Don't worry

**Comment by swiftyspiffy** [comment]
So I was having some disconnect issues that forced me to revert Burke's bot back to the main branch build, but will continue to play around with and see why the disconnects occur.

**Comment by prom3theu5** [comment]
Any idea where the disconnect was occurring?
Was the remote port forcibly closed?

I've yet to have any disconnects which is strange. I'm logging to SEQ through Serilog in both TwitchLibs events, and the WebSocketWrappers events

How about PuBSub are you getting drops on that connection?
 Maybe an issue with Microsoft.Net.Websockets.Client under mono.

**Comment by swiftyspiffy** [comment]
I think the issue is related to using an old library or something. Give me a bit of time to work through this. Will continue to update this issue.

**Comment by prom3theu5** [comment]
Sure thing man :)
Good luck

**Pull request merged**
