### PR TITLE
LiveStreamMonitor Service

### PR DESCRIPTION
**Pull request by elu00**
This service creates the event requested in #144 , and also attaches a OnChannelOffline event.
However, the constructor for the service is fairly awkward in that it requires a `List<JoinedChannel>` as a list of channels to monitor. As such, I'll try to fix this prior to merging this PR. Just putting this up for discussion :smile:

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
This was the post I made over on the issue discussing this.

Looks good, just a couple recommendations I'd make:
- Modify the namespace in each of the events from TwitchLib.Events.Services.FollowerService to TwitchLib.Events.Services.LiveChannelMonitor
- Kind of nitpicky, but I would change the name from LiveChannelMonitor to LiveStreamMonitor, since the Twitch API differentiates the two (channel objects always exist (unless user is banned or something) and stream objects only exist while the stream is active.
- I think the ClientId value should be accessible from TwitchAPI, that way we're always sourcing this value from the same place. (it looks like this needs to be applied to FollowerService as well).
- As you mentioned, we probably want to pass in a list of strings that represent the channels/streams to watch.
- Additionally, we also might want to accept a list of strings representing channel/user IDs as an overloaded constructor so that we account for the move from usernames -> user id's.
- Another nitpicky thing, perhaps move the #Events region to at the top so that someone viewing the code would immediately know the events to subscribe to.

Other than that, looks good. Thanks a ton :)

**Comment by swiftyspiffy** [comment]
I can add those fixes if you want, or you are welcome to take a stab. Let me know.

**Comment by elu00** [comment]
Ah oops, guess you can tell I copypasted a lot from the FollowerService lol.
Alright sure, I'll be trying to add those fixes tonight.
Thanks!

**Comment by swiftyspiffy** [comment]
No proble, I do the same thing haha. All about consistency 👍

**Comment by elu00** [comment]
Alright, all of the namespace/typo stuff should be fixed now.
As far as the ClientID value goes, since it isn't used anywhere in the service itself, shouldn't we be ok internalizing it within TwitchAPI? I thought the only purpose of ClientID in the services was to override the existing ClientID if necessary.

Channels are also stored as strings now, which should make everything better lol.
Does BroadcasterOnlineAsync handle parsing userids, or do we need to validate/call a different function if userids are passed in?
Thanks!

**Comment by swiftyspiffy** [comment]
Actually you're right. I think we'd want to default to the TwitchApi Client ID, but if give the user the ability to pass in a client ID that the service would use instead of the TwitchApi client ID.

This presents an interesting problem. Because both usernames and user ids are strings (per Twitch API specification), there's no clear way to differentiate between a user id and a username that happens to look like a user id. Indeed, a username could match a user id exactly. Ideally, we'd do what Twitch would want us to do and only accept user ids, but I'm guessing the majority of users of the library would want the ability to specify a username. I'm actually not quite sure what we should do.

**Comment by vaindil** [comment]
This looks like an inconsistency on Twitch's end. The [Get Channel Editors endpoint](https://dev.twitch.tv/docs/v5/reference/channels/#get-channel-editors) returns an array of users that have a numeric ID, not a string. Channel followers uses a string ID, channel subscribers is numeric. I'll make a post on the dev forum there asking why they aren't all numeric.

**Comment by swiftyspiffy** [comment]
I spoke to a Twitch dev, and he said that all endpoints should be string (they're working on changing them), and that any implementation of their API should treat user ids as strings because other products may introduce user ids that are strings, and to be globally safe, they should all be strings. This obviously complicates making the username and user id differentiation.

I think Twitch would say that we should treat all inputs as user ids, period. But, obviously that's not very convienent for 95% of the users of the library.

**Comment by vaindil** [comment]
Yeah, I agree, using IDs would be great, just not feasible with the info the API provides IMO. My bot has a crappy little points system, it has to use username because there's no way to get the ID of a mentioned user from the message itself. (Discord has a separate property in the response with the user object of everyone who was mentioned in the message, it's really handy.)

As much as I hate the idea, I don't know if there's a way other than multiple functions with names signifying whether the string parameter is an ID or a username.

**Comment by elu00** [comment]
Alright, are there any changes with the username/userid distinction we can address within the scope of this service, or should this be implemented elsewhere in the library? Unfortunately I'm familiar at all with the specifics of the API, so I don't really have anything to add here :( 
Thanks!

**Comment by swiftyspiffy** [comment]
So here is what I recommend we do:
- Constructor of LiveStreamMonitor accepts simply checkIntervalSeconds and clientId.
- We have two public methods, one called `SetStreamsByUsername(List<string> usernames)` and `SetStreamsByUserId(List<string> userids)`
- If the user attempts to start the service without username(s) or userid(s) set, then we need to throw an exception and inform them, and to do this we need:
- An exception designated for this purpose
- In addition to the the methods listed above, we also need to distinguish between the two api endpoints that we want to hit (v5 for userids, v3 for usernames). To do this I recommend we make an enum as such:
```
enum StreamIdentifierType {
      Usernames,
      UserIds
}
```
- In SetStreamsByUsernames, we'd set the usernames to a private list instance variable and we'd set a private instance variable to the enum value Username.
- In SetStreamsByUserIds, we'd set the userids to a private list instance variable and we'd set a private instance variable tot he enum value UserIds.
- Finally, when we go to check the actual stream status, we refer to the enum value we set to know which endpoint we should hit with the stream value (either username or userid).

This is a bit of work, but it should make it ultra clear which endpoint we should be querying so the user of the library doesnt screw it up.

**Comment by elu00** [comment]
Oops, looks like my previous comment didn't come through.
Sure, that all sounds good! 
I'll take a crack at trying to implement some of this as well; not sure how far I'll be able to get though haha.
Should we be looking at a new PR for the v5 stuff, or should we just lump it all in with this PR?

**Comment by swiftyspiffy** [comment]
This looks good and almost ready to merge. I'd just ask that you rebase and fix the merge conflicts that Github is saying exist and then we should be good.

Thanks again :)

**Comment by elu00** [comment]
Alright great! I think I've rebased and fixed all the merge conflicts already, so we hopefully should be good on that front. I'll try to polish up the exception handling/XML in the next couple days. However, I haven't actually implemented the v5 API stuff yet, since I'm not super familiar with the API itself; would you mind looking into that?

Also, no problem! I'm super happy to be able to contribute to such a great library :)

**Pull request merged**
