### PR TITLE
Massive API update / improvement / overhaul. [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by Nadermane**
This is the first commit in a series of commits that will ultimately expand and refactor the API portion of the project. This project isn't finished by a long shot, so this is not material to be merged as of writing, this is buggy as all hell most likely, although some stuff might work. All old API stuff hasn't changed at all so that's all still functional. I plan on adding EVERY SINGLE API ENDPOINT to this PR, which should be really darn useful. I will be working on this over multiple days, so yeah, be on the lookout for it. This commit is just to show you what I'm doing and to get feedback on certain endpoints' documentation etc. As always, hope it helps!

A list of changes so far:
- Move model files into Models/ folder (without changing namespace)
- Update all properties and make them all auto-accessors.
- Add TwitchFeedPost model. (WIP, not tested yet)
- Update TwitchStream model to add email and stream_key.
- Get rid of TwitchAPI.cs completely, we're doing something cooler here.
- Implement APIBase for helper functions and definitions.
- New Block API methods: GetBlockList, BlockUser, UnblockUser
- New Channel-Feed API methods: GetFeedPosts, AddFeedPost, GetFeedPost, DeleteFeedPost, ReactToFeedPost, DeleteFeedPostReaction
- New Channels API method: GetOwnTwitchChannel (including email and stream_key)
- Generate new API class stubs.
- Cleanup usings.

### CODE REVIEW

**Comment by Nadermane** [comment]
And that's it for now. More coming soon. Started work on the next API endpoint categories; channels and chat.

**Comment by swiftyspiffy** [comment]
Awesome, looks great.  I was going to work on implementing Client-ID tokens in API calls (per: [Client-ID Requirement](https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108)), but I'll hold off for your refactoring so as to not get merge conflicts later on.

NuGet library has been updated with the XML documentation file per your request ([NuGet Gallery | TwitchLib](https://www.nuget.org/packages/TwitchLib/1.0.3)).

Thanks again!

**Comment by Nadermane** [comment]
Client-ID tokens implemented. It now enforces that either an access token (OAuth token) is provided with the request OR that the SetClientId method is used to set the Client-ID to use.

**Comment by Nadermane** [comment]
Sorry for being slow with this PR, stuff has happened and I haven't yet had enough time to continue. I will continue soon enough though. 👍

**Comment by swiftyspiffy** [comment]
No worries, it's all good, there's no rush on any of this. As a side note, I have added support for badges via a property in ChatMessage. As such, make sure you pull down the changes when you get a chance. Additionally, an impending change to subscriber chat notifications is imminent, and code changes are required to account for it ([Resubscription Changes](https://discuss.dev.twitch.tv/t/important-re-subscription-change/6463)).

Finally, I will be updating the NuGet package tomorrow or Monday with the Badges changes, as well as an AutoConnect=true change (which fixed the issue I was having).

**Comment by swiftyspiffy** [comment]
Also feel free to modify the logic regarding the badges, the code I just pushed is more or less a placeholder to allow for accessing the property, and to fix the incorrect parse job.

**Comment by swiftyspiffy** [comment]
This pull request is significantly out of date with the current code base. If you are still interested in merging, perhaps you can rebase and repush the new version and reopen this. I will close this for now. :dancer:

**Pull request closed without merging**
