### PR TITLE
Crash fix and some comments

### PR DESCRIPTION
**Pull request by igor523**
Hello!
Commits description will tell all what you need to know =)

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
This looks good. I would just ask one addition. Since you're right that queryCount is never used, could you commit code to set QueryCount to queryCount in the constructor? As such:

```
public FollowerService(string channel, int checkIntervalSeconds = 60, int queryCount = 25, string clientId = "")
{
       Channel = channel;
       CheckIntervalSeconds = checkIntervalSeconds;
       QueryCount = queryCount;
       _followerServiceTimer.Elapsed += _followerServiceTimerElapsed;
       if (clientId != "")
            ClientId = clientId;
}
```

Other than that, thanks!

**Comment by swiftyspiffy** [comment]
Not sure where my previous message went. But two things. 

1. If you could commit code so that queryCount is used (in other words, in the constructor set QueryCount = queryCount), as intended.
2. Regarding the null check on ActiveCache, I think I did that because `await TwitchApi.Follows.GetFollowersAsync(Channel, QueryCount);` can return null if it fails.

**Comment by igor523** [comment]
Done! Sorry, haven't checked mail for a while

**Comment by swiftyspiffy** [comment]
Thanks igor!

**Comment by igor523** [comment]
No problem! =)

**Pull request merged**
