### PR TITLE
Ditched Meebey Entirely

### PR DESCRIPTION
**Pull request by prom3theu5**
Switched to the web socket wrapper for the actual IRC connection.
I added a very basic test console client for your evaluation.

This is what I mentioned at the end of the issue I opened regarding a port of SmartIrc4net to .NetStandard.

This is just here for evaluation now, would need to leave it running for a while, log messages / message counts with both clients and see how it holds up. It's basically the implementation twitch use themselves on the website.

Gets you down to 0 non Microsoft dependencies =)
(Well.. Newtonsoft.Json, but still :P)

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Good work! Wow, I was planning on doing this when I got some free time from school but wow, this is awesome! I'll test it quite a bit before merging because it's an integral part of the library, so I want to make sure it's really stable.

Regarding Newtonsoft, ya there's no real way of getting around a json dependency I think. 3ventic offered Jil, a slightly more efficient json library, but it's not really important.

Going forward, I think I'm going to completely rewrite the parsing for events/messages  because right now time complexity is like quadratic, for no real reason.

Anyways, I digress. Will test this and merge!

**Comment by prom3theu5** [comment]
Np man :)

There could be a bit of work required with reconnecting - possibility that the websocket isn't fully closed on a crash, but we will see :)

It's important to note Sends have to be done Synchronously over websockets

**Comment by swiftyspiffy** [comment]
So a few things:
1. I merged this pull request into its own branch by the name of `remove_smartirc4net` ( https://github.com/swiftyspiffy/TwitchLib/tree/remove_smartirc4net ). Feel free to check that out and make pull requests to it as issues are discovered with the websocket client.
2. I just committed a fix for the \r\n appended to each irc message received by Trimming. This should suffice for this. Commit: 45dc25717f6d1717713c06d9116540ceaad7ead4
2. IsConnected is not being set to true I think because OnConnected is not firing (there might be a parsing issue that is causing this). This is a problem because a number of implementations I've seen rely on IsConnected to determine whether or not it's safe to send a message. I wasn't able to figure this one out in the limited time I had, but I'll give it another go tonight or tomorrow.

**Comment by prom3theu5** [comment]
Cool man :)

We might be able to just use the state of the WebSocket, like this:

```c#
public bool IsConnected
{
 get
   {
      return Client.State == WebSocketState.Open;
   }
}
```

**Comment by swiftyspiffy** [comment]
Ohhh, good idea. Will commit that now.

**Comment by prom3theu5** [comment]
I've found why the connection event isn't processed.
It seems over the web sockets connection, the initial message from twitch on open is combined.
A single string is received:

":tmi.twitch.tv 001 prom3theu5 :Welcome, GLHF!\r\n:tmi.twitch.tv 002 prom3theu5 :Your host is tmi.twitch.tv\r\n:tmi.twitch.tv 003 prom3theu5 :This server is rather new\r\n:tmi.twitch.tv 004 prom3theu5 :-\r\n:tmi.twitch.tv 375 prom3theu5 :-\r\n:tmi.twitch.tv 372 prom3theu5 :You are in a maze of twisty passages, all alike.\r\n:tmi.twitch.tv 376 prom3theu5 :>"

**Pull request merged**
