### PR TITLE
Adds sync/async GetAllChannelSubscribers

### PR DESCRIPTION
**Pull request by prom3theu5**
I noticed yesterday that the project has been restructured considerably since I initially checked this months ago. 
Looking great now, well done =)

I made the decision to ditch my library and switch to this tonight for my Streamers bot, however during implementation I noticed a method I needed was missing. The ability to pull a full list of subscribers rather than making multiple API calls to check whether a user was a subscriber or not.

I've added it. Tried to keep it inline with your current restructuring. You may decide to add or may have left out for a reason, but it's here if you decide to merge :)

Returns a Response with List of type User,  and int (Count)

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
I didn't see this before pushing my code just a second ago, so I can resolve the conflict in a second. Would you mind walking me through this. It looks like it's making repeated requests and fetching 90 subscribers at a time? What is the reason for 90, versus say the max of 100? Other than it looks good!

Thanks a ton!

**Comment by prom3theu5** [comment]
Hey man
I know BurkeBlack - I occasional jump in and watch, he is an awesome streamer!

Do you handle all his infrastructure?
Nice job if that's the case, you've given him a lot of cool features :)

You're right, my bad. I should have set to the maximum page size of 100. 
I use 90 because one of Doc's "toys" splits subs into groups of 9 :P

Basically it rounds up the result of totalSubs / pageSize, then just performs a request for each page required, shifting the offset, and appends the subscriber collection with the returned page subscribers array.

**Comment by swiftyspiffy** [comment]
Yup, I do all of Burke's infrastructure! Thanks man, means a lot coming from someone like you!

Anyways, I just made the conflict resolution commit and the build is failing because it's missing the ChannelSubscribersResponse.cs class. I will merge this and it should resolve that issue.

Additionally, I might work ont his a bit if you don't mind and update it for more general use.

**Comment by prom3theu5** [comment]
Sure thing - have your wicked way with it :P
Thanks a lot man :)

**Pull request merged**
