### PR TITLE
Page Size and Fix

### PR DESCRIPTION
**Pull request by prom3theu5**
Upped max page size to 100, also fixed an error 😊 
Would have skipped the last page of subs - sorted now.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
I actually think I've got it covered :D. Let me know what you think. I tested it using Burke's 2042 subscribers and it appears to work. I put a delay of 1 second between requests because Twitch doesn't like it when you do more than 1 request per second. Let me know what you think, here's the GetAllChannelSubscribers function I wrote: https://github.com/swiftyspiffy/TwitchLib/commit/ce10d524d68896747704116fa8c11322f980f8e0

**Comment by swiftyspiffy** [comment]
I did some slight naming changes and also the way the models are handled was slightly changed.

**Comment by prom3theu5** [comment]
Looking good man

Nice addition being able to pull x number of subs too, from page y. I had in mine, but wasn't sure if I'd need in the future, so didn't add it - but for the sake of completeness it's good having it exposed as a public method like that.

Use case example: Pull last 10 subs etc if you aren't tracking :)

I like it

**Comment by swiftyspiffy** [comment]
Ya, it's really something that should have been in there a long time ago, not sure why it wasn't. Thanks again though!

**Pull request closed without merging**
