### PR TITLE
Fixed OnCallMessage bug in WebSocketClient

### PR DESCRIPTION
**Pull request by prom3theu5**
Was causing the parse errors we were seeing.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Looks like there's an issue with Newtonsoft on that commit. Is it possible the version adjustment messed something up?

**Comment by prom3theu5** [comment]
I removed all packages, and readded, as the last time I'd removed them I simply removed the reference, not the nuget package - so nuget figured they were still installed.

Nuget referenced version of Json.Net changed from 7 to 9.0.1 too.

**Comment by swiftyspiffy** [comment]
I'm not exactly sure. I too am having a NuGet issue on a separate project, which I'm trying to solve right now. If it's easy for you to resolve that issue, go for it, otherwise I can spend some time on it here in a bit.

**Comment by prom3theu5** [comment]
It's cool man - I'll sort now

**Pull request closed without merging**
