### PR TITLE
API ExpiredTokenException and Refresh Token Method for the API

### PR DESCRIPTION
**Pull request by Syzuna**
Hey swiffty!

I put sth together that catches an expired token response and throws an exception.
It worked quite well for me until now.

But bcs this is hard to test and maybe not the cleanest way I would say we put this for discussion for 1-2 days so ppl can review it and maybe make some own tests and throw in some improvement thoufhts? Your decision.

Regards

Syzuna

PS: For catching IRC login fails due to an expired token you can use the InvalidLogin event from the client! Bcs Twitch just throws this for an invalid token while logging into the IRC server

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
This does look promising, but you're right, it's a bit hard to test. Will link to issue: #298

**Comment by Syzuna** [comment]
@swiftyspiffy will add a API section to this PR with a call that gets a refreshed token and a new refresh token from the api. It wont do that by its own bcs of the secret but with that its easier if you have a secret present bcs you just pass in the refresh token and the secret and you are all set!

**Comment by Syzuna** [comment]
dont ask me why it made this dumb diff overwatch for the API class

**Comment by Syzuna** [comment]
ok now I am done I hope :D sorry for that rly big pr and all that comments but forgot some things here and there. In the future I will try to avoid sth this big.

**Comment by swiftyspiffy** [comment]
So was the only thing changed in TwitchApi.cs the following?
```
case HttpStatusCode.Unauthorized:
                    var authenticateHeader = errorResp.Headers.GetValue("WWW-Authenticate");
                    if(string.IsNullOrEmpty(authenticateHeader))
                        throw new BadScopeException("Your request was blocked due to bad credentials (do you have the right scope for your access token?).");

                    var invalidTokenFound = authenticateHeader.Contains("error='invalid_token'");
                    if(invalidTokenFound)
                        throw new TokenExpiredException("Your request was blocked du to an expired Token. Please refresh your token and update your API instance settings.");
                    break;
```
The diff is hard to see changes with.

**Comment by Syzuna** [comment]
Yeah thats the only thing I changed there iirc. I just used the spare information twitch gives you on that.

**Comment by Syzuna** [comment]
bcs I cant get it to rebase correctly I will remake my fork and reapply changes to the new fork to make a new PR (git noob at work sadly)

**Comment by swiftyspiffy** [comment]
All good, no worries.

**Pull request closed without merging**
